Repository team-TEN-TEN/damoa-server, pull requests merged in 2024-08, with the labels that each got.

#6 [feat] 에러 응답, 에러 코드 및 커스텀 에러 정의
  src/main/java/com/tenten/damoa/common/exception/BusinessException.java
  src/main/java/com/tenten/damoa/common/exception/ErrorCode.java
  src/main/java/com/tenten/damoa/common/exception/ErrorResponse.java
Labels: feature

#10 [env] RDS 계정 정보 및 엔드포인트 설정
  src/main/resources/application-dev.yml
Labels: env

#14 [feat] 전역 에러 처리기 설정
  src/main/java/com/tenten/damoa/common/exception/ErrorCode.java
  src/main/java/com/tenten/damoa/common/exception/ErrorResponse.java
  src/main/java/com/tenten/damoa/common/exception/GlobalExceptionHandler.java
Labels: feature

#12 [env] ci 워크플로우 작성
  .github/workflows/ci.yml
  src/main/resources/application-prod.yml
Labels: env

#13 [chore] 결원으로 인한 code owners 수정
  .github/CODEOWNERS
Labels: chore

#21 [feat] entity, repository 생성
  src/main/java/com/tenten/damoa/DamoaApplication.java
  src/main/java/com/tenten/damoa/common/model/BaseEntity.java
  src/main/java/com/tenten/damoa/hashtag/domain/Hashtag.java
  src/main/java/com/tenten/damoa/hashtag/repository/HashtagRepository.java
  src/main/java/com/tenten/damoa/interactionhistory/domain/Category.java
  src/main/java/com/tenten/damoa/interactionhistory/domain/InteractionHistory.java
  src/main/java/com/tenten/damoa/interactionhistory/repository/InteractionHistoryRepository.java
  src/main/java/com/tenten/damoa/member/domain/Member.java
  src/main/java/com/tenten/damoa/member/domain/MemberRole.java
  src/main/java/com/tenten/damoa/member/repository/MemberRepository.java
  src/main/java/com/tenten/damoa/post/domain/Post.java
  src/main/java/com/tenten/damoa/post/domain/SnsType.java
  src/main/java/com/tenten/damoa/post/repository/PostRepository.java
  src/main/java/com/tenten/damoa/verificationcode/domain/VerificationCode.java
  src/main/java/com/tenten/damoa/verificationcode/repository/VerificationCodeRepository.java
  src/main/resources/application-local.yml
  src/main/resources/db/migration/V1__init.sql
Labels: feature

#25 [refactor] 도메인 패키지, 클래스 이름 재정의
  src/main/java/com/tenten/damoa/interaction/domain/InteractionCategory.java
  src/main/java/com/tenten/damoa/interaction/domain/InteractionHistory.java
  src/main/java/com/tenten/damoa/interaction/repository/InteractionHistoryRepository.java
  src/main/java/com/tenten/damoa/interactionhistory/domain/Category.java
  src/main/java/com/tenten/damoa/verification/domain/VerificationCode.java
  src/main/java/com/tenten/damoa/verification/repository/VerificationCodeRepository.java
Labels: enhancement

#26 [chore] API 시연을 위한 dummy data 추가
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: chore

#36 [feat] 회원가입 API
  build.gradle
  src/main/java/com/tenten/damoa/common/config/SecurityConfig.java
  src/main/java/com/tenten/damoa/common/exception/ErrorCode.java
  src/main/java/com/tenten/damoa/common/util/RandomCodeUtil.java
  src/main/java/com/tenten/damoa/common/util/RegexPatternUtil.java
  src/main/java/com/tenten/damoa/member/controller/MemberController.java
  src/main/java/com/tenten/damoa/member/controller/request/RegisterMemberReq.java
  src/main/java/com/tenten/damoa/member/controller/response/RegisterMemberRes.java
  src/main/java/com/tenten/damoa/member/domain/Member.java
  src/main/java/com/tenten/damoa/member/repository/MemberRepository.java
  src/main/java/com/tenten/damoa/member/service/MemberRegisterService.java
  src/main/java/com/tenten/damoa/verification/domain/VerificationCode.java
  src/test/java/com/tenten/damoa/member/controller/MemberControllerTest.java
  src/test/java/com/tenten/damoa/member/service/MemberRegisterServiceTest.java
Labels: feature

#29 [feat] 게시물 상세 API
  src/main/java/com/tenten/damoa/common/model/BaseEntity.java
  src/main/java/com/tenten/damoa/interaction/domain/InteractionHistory.java
  src/main/java/com/tenten/damoa/post/controller/PostController.java
  src/main/java/com/tenten/damoa/post/domain/Post.java
  src/main/java/com/tenten/damoa/post/service/PostQueryService.java
Labels: feature

#38 [feat] 해시태그별 통계 조회 API
  build.gradle
  src/main/java/com/tenten/damoa/common/config/QueryDslConfig.java
  src/main/java/com/tenten/damoa/common/exception/ErrorCode.java
  src/main/java/com/tenten/damoa/stat/controller/StatController.java
  src/main/java/com/tenten/damoa/stat/controller/dto/HashtagStatRes.java
  src/main/java/com/tenten/damoa/stat/domain/MetricsType.java
  src/main/java/com/tenten/damoa/stat/domain/Period.java
  src/main/java/com/tenten/damoa/stat/domain/TimeUnit.java
  src/main/java/com/tenten/damoa/stat/repository/StatRepository.java
  src/main/java/com/tenten/damoa/stat/repository/StatRepositoryImpl.java
  src/main/java/com/tenten/damoa/stat/service/HashtagStatQueryService.java
  src/main/java/com/tenten/damoa/stat/service/command/HashtagStatCommand.java
Labels: feature

#32 [feat] 회원승인 API #23
  src/main/java/com/tenten/damoa/common/exception/ErrorCode.java
  src/main/java/com/tenten/damoa/member/domain/Member.java
  src/main/java/com/tenten/damoa/member/repository/MemberRepository.java
  src/main/java/com/tenten/damoa/post/repository/PostRepository.java
  src/main/java/com/tenten/damoa/verification/controller/VerificationController.java
  src/main/java/com/tenten/damoa/verification/dto/VerificationReq.java
  src/main/java/com/tenten/damoa/verification/repository/VerificationCodeRepository.java
  src/main/java/com/tenten/damoa/verification/service/VerificationService.java
  src/main/resources/data.sql
Labels: feature

#33 [feat] 게시글 좋아요 API #31
  src/main/java/com/tenten/damoa/common/config/RestTemplateConfig.java
  src/main/java/com/tenten/damoa/common/exception/ErrorCode.java
  src/main/java/com/tenten/damoa/interaction/domain/InteractionHistory.java
  src/main/java/com/tenten/damoa/post/controller/PostController.java
  src/main/java/com/tenten/damoa/post/domain/Post.java
  src/main/java/com/tenten/damoa/post/domain/SnsType.java
  src/main/java/com/tenten/damoa/post/service/PostService.java
Labels: feature

#34 [feat] 게시물 공유 API
  src/main/java/com/tenten/damoa/interaction/domain/InteractionHistory.java
  src/main/java/com/tenten/damoa/post/controller/PostController.java
  src/main/java/com/tenten/damoa/post/domain/Post.java
  src/main/java/com/tenten/damoa/post/service/PostShareService.java
  src/main/java/com/tenten/damoa/verification/controller/VerificationController.java
  src/main/resources/application-local.yml
  src/main/resources/data.sql
Labels: feature
